config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :courses do

    resources :bookings, only: [:create, :show]
    resources :reviews, only: [:new, :create, :destroy]
  end
  resources :bookings, only: [:index , :destroy,:update]
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :course
  belongs_to :user
  has_one_attached :photo

  before_create :set_room_name

  # callback ActiveRecord 
  def set_room_name
    client = Twilio::REST::Client.new(ENV["KEY_ID"], ENV["AUTH_TOKEN"])
    room = client.video.rooms.create(unique_name: "#{course.title}_#{Time.now.to_i}")
    self.url_room = room.unique_name
  end
end

app/models/course.rb
class Course < ApplicationRecord
  # has_many :users, through: :bookings
  has_many :bookings, dependent: :destroy
  belongs_to :user
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :courses
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings
    @teacher_bookings = current_user.courses.map(&:bookings).flatten
  end

  def new
    @booking = Booking.new
  end

  def show
    @booking = Booking.find(params[:id])
    @token=generate_token(@booking)
  end

  def create
    @course = Course.find(params[:course_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.course = @course
    if @booking.save!
      flash[:notice] = 'Course has been successfully booked'
      redirect_to bookings_path
    else
      render 'courses/show'
    end
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to bookings_path

    else
      flash[:error] = 'You fucked up ! , please try again'
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @course = Course.find(@booking.course_id)
    if @booking.destroy
      flash[:success] = 'Booking has been cancelled'
    else
      flash[:error] = 'You fucked up ! , please try again'
    end
    redirect_to bookings_path
  end

  private

  def get_booking_date(params)
    "#{params["date(3i)"]}/#{params["date(2i)"]}/#{params["date(1i)"]}"
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :photo)
  end

  def generate_token(booking)
    
    token = Twilio::JWT::AccessToken.new ENV['ACCOUNT_SID'], ENV['KEY_ID'], ENV['AUTH_TOKEN'], [],
        ttl: 14400,
        identity: current_user.email
   
    grant = Twilio::JWT::AccessToken::VideoGrant.new
    grant.room = booking.url_room
    token.add_grant grant
    
    token.to_jwt
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:destroy]
  def index
    if params[:query].present?
      @courses = Course.where("title ILIKE ?", "%#{params[:query]}%")
    else
      @courses = Course.all
    end
  end

  def search
    @course = Course.search(params[:search])
  end

  def new
    @course = Course.new
  end

  def show
    @booking = Booking.new
    @course = Course.find(params[:id])
    @bookings = @course.bookings
    @bookings_dates = @bookings.map do |booking|
      {
        from: booking.start_date, to:   booking.end_date
      }
    
    end
  end

  def create
    @course = Course.new(course_params)
    @course.user = current_user
    if @course.save
      flash[:notice] = 'Course has been successfully created'
      redirect_to course_path(@course)
    else
      render 'course/new'
    end
  end

  # def update
  #   @course = Course.find(params[:id])
  #   @course.update(course_params)
  #   flash[:notice] = 'course information has been updated'
  #   redirect_to course_path
  # end

  def destroy
    @course.destroy
    redirect_to courses_path
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description, :photo_url, :duration, :price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def index
        @reviews = current_user.reviews
      end

      def new
        @new_review = Review.new
        @course = Course.find(params[:course_id])
      end
    
      def create
        @new_review = Review.new(review_params)
        @new_review.user = current_user
        @course = Course.find(params[:course_id])
        @new_review.course = @course #thibo 
      
        if @new_review.save
          redirect_to course_path(@course)
        else
          flash[:alert] = "Something went wrong."
          render :new
        end
      end
    
      def destroy
        @review = Review.find(params[:id])
        @review = Course.find(@review.course_id)
        if Review.delete(params[:id]).positive?
          flash[:success] = 'Review has been deleted'
        else
          flash[:error] = 'please try again'
        end
        redirect_to review_path(@review)
      end
      private

      def review_params
        params.require(:review).permit(:comment, :rating, :course_id)
      end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
  <h1>my booking list</h1>
  <div class="d-flex row justify-content-center">
      <% @bookings.each do |booking| %>
        <div class="col-lg-4">
          <div class="card bg-light my-3">
            <div class="btn" style="margin-bottom: 10px;">
              <%= link_to  "Go to class", course_booking_path(booking.course,booking) %>
            </div>
              <%= image_tag(booking.course.photo_url, height: 300) %>
            <div class="card-body d-flex align-items-center">

            </div>
            <div class="card-body">
              <ul class="list-group list-group-flush">
                <li class="list-group-item booklist"> schedule date: <%= booking.start_date %></li>
                <li class="list-group-item booklist"> schedule date: <%= booking.end_date %></li>
              </ul>
            </div>
            <div class="trash-link">
              <%= link_to booking_path(booking),
              method: :delete,
              data: { confirm: "Are you sure?" }, class: 'card-remove-link' do %>
              <span style="font-size: 2em; color: black;">
              <i class="fas fa-trash-alt  "></i>
              </span>
              <% end %>
            </div>
          <%= simple_form_for(booking) do |f| %>
            <!-- [...] -->
            <%= f.input :photo, as: :file %>
           <%=f.button :submit, class:"btn btn-danger"  %>
          <% end %>
          <% if booking.photo.attached? %>
          <%= cl_image_tag booking.photo.key, height: 150, width: 300, crop: :fill,
          class: "booking_index_image" %>
          <% end %>
          </div>
        </div>
      <% end %>
  </div>
</div>



<div class="d-flex justify-content-center">
 <div class="justify-content-center">
   <%= link_to "Back To course List",  courses_path, class: "btn btn-primary"%>
   <%= link_to "Home",  root_path, class: "btn btn-primary"%>
 </div>
</div>


<div class="container">
  <div class="d-flex row justify-content-center">
    <% @teacher_bookings.each do |booking| %>
      <div class="col-lg-4">
        <div class="card bg-light my-3">
          <div class="btn" style="margin-bottom: 10px;">
            <%= link_to  "Go to class", course_booking_path(booking.course,booking) %>
          </div>
          <%= image_tag(booking.course.photo_url, height: 300) %>
          <div class="card-body d-flex align-items-center">

          </div>
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li class="list-group-item booklist"> schedule date: <%= booking.start_date %></li>
              <li class="list-group-item booklist"> schedule date: <%= booking.end_date %></li>
            </ul>
            <div class="trash-link">
              <%= link_to booking_path(booking),
                method: :delete,
                data: { confirm: "Are you sure?" }, class: 'card-remove-link' do %>
                <span style="font-size: 3em; color: Mediumslateblue;">
                <i class="fas fa-trash-alt  "></i>
                </span>
              <% end %>
            </div>
          </div>
          <%= simple_form_for(booking) do |f| %>
            <!-- [...] -->
            <%= f.input :photo, as: :file %>
           <%=f.button :submit, class:"btn btn-danger"  %>
          <% end %>
          <% if booking.photo.attached? %>
          <%= cl_image_tag booking.photo.key, height: 150, width: 300, crop: :fill,
          class: "booking_index_image" %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>
 

app/views/bookings/show.html.erb
<div class="title-wrapper">
  <div class="container">
    <h1 class="title">Your online class</h1>
  </div>
</div>



<div class="container">
  <div 
    class="twilio-video" 
    data-sid="<%= ENV["ACCOUNT_SID"] %>" 
    data-room="<%= @booking.url_room %>" 
    data-token="<%= @token %>"
    >

    <div class="row justify-content-center">
      <div class="col-6">
        <div class="participant">
        </div>
      </div>
      <div class="col-6">
        <div class="remote-media-div text-center">
          <video id="userVideo" autoplay muted="true" ></video>
          <div>
            <button id='leave-btn' class='btn btn-primary mt-3'> 
              Quit Session
            </button>
          </div>
        </div>
      </div>
    </div>
   <% if @booking.course %>
    <div class="row">
      <div class="col-7">
      <p class="text-center">
        <%=  @booking.user == current_user ? @booking.course.user.email : @booking.user.email %>
      </p>
      </div>
    </div>
      <% end %>
    <%= link_to '', root_path, class: 'd-none root-link', data: {turbolinks: false}  %>

   <div class="btn">
 <%= link_to  "create your review", new_course_review_path(@booking.course) %>
 </div>

  </div>
</div>

app/views/courses/index.html.erb
<div class="container">
  <h1>Our <span>course</span> list</h1>
    <h4>Take a look at our best courses:</h4>
    
<div class="btn"> 
<%= link_to  "create your course", new_course_path %>
</div>

  <div class="d-flex row justify-content-center">
    <% @courses.each do |course| %>
      <div class="col-lg-4">
        <div class="card bg-light my-3">
          <%= image_tag(course.photo_url, height: 300) %>
          <div class="card-body d-flex align-items-center">
            <div class="">
              <h3 class="card-title fw-bolder"> <%= course.title %> </h3>
            </div>
          </div>
          <div class="card-body">
            <%= link_to "Learn more",  course_path(course), class: "btn btn-booknow card-link"%>


          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/courses/new.html.erb
<div class="form-login">
<%= simple_form_for(@course) do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :duration %>
  <%= f.input :price %>
  <%= f.input :photo_url %>
  <%= f.button :submit, "create course", class: "btn btn-primary" %>
<% end %>
</div>

app/views/courses/show.html.erb
<div><h1> </h1></div>
<div class="container">
  <div class="row">
    <div class="col-9 col-lg-7">
      <div class="card">
        <h1><%= @course.title %></h1>
        <img class="card-img-top" src="<%= @course.photo_url %>
        " alt="Card image cap">
        <div class="card-body">
          <p class="card-text"> <%= @course.title  %>  </p>
          <p>Description <%= @course.description  %> </p>
          <p><i class="fas fa-clock"style="margin-right:0.5em"></i><%= @course.duration  %> </p>
          <p><i class="far fa-money-bill-alt"style="margin-right:0.5em">   </i><%= @course.price  %> </p>
        </div>
      </div>
    </div>

    <div class="col-12 col-lg-4">
      <div class="card286">
            <div class="container">
              <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
               <h2><strong>Book a Course</strong></h2>

                <%= simple_form_for [@course , @booking]  do |f| %>
                  <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
                  <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
                  <%= f.button :submit, "book", class: "btn btn-primary" %>
                <% end %>
              </div>
            </div>


       
<%  @course.reviews.each do |review|   %>
<div class = "review">
<%= review.comment %>
<%=  "⭐" * review.rating  %> 
</div>
<% end  %>
<br></br>


 



</div>
<br></br>

<div class="card">
    <img src="https://scontent.fmru7-1.fna.fbcdn.net/v/t1.6435-9/90305980_239715910399706_2193308204564217856_n.jpg?_nc_cat=108&ccb=1-5&_nc_sid=09cbfe&_nc_ohc=IzRECa72wfEAX8Opsmw&_nc_ht=scontent.fmru7-1.fna&oh=e5611553918c7f2b3558a3f50899485d&oe=61BCEEA2" alt="">
    <h3>Jivesh</h3>
    <p>French with literature (Bachelors) - Nottingham University<br></br>Hi, I'm Jivesh, a second year French undergrad at the University of Nottingham.
    Personally I've always been a fan of French with literature.</br></p>
    <div class="icons">
        <a href="#" class="fab fa-facebook-f"></a>
        <a href="#" class="fab fa-twitter"></a>
        <a href="#" class="fab fa-instagram"></a>
        <a href="#" class="fab fa-github"></a>
    </div>
</div>



          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTutors2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %> 
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <%= render 'shared/footer' %>
    <script src="https://media.twiliocdn.com/sdk/js/video/v1/twilio-video.min.js"></script>
  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Complete Responsive Pet Food Website Design Tutorial</title>
</head>
<body>
<!-- home section starts  -->
<section class="home" id="home">
    <div class="content">
        <h3> <span>hi</span> welcome to my_tutors </h3>
        <div class="search">
       <%= form_tag courses_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find a tutor . . ."
        %>
        <%= submit_tag "Search", class: "btn " %>
       <% end %>
    </div>
    </div>
<%= image_tag "bottom_wave.png", class: "wave" %>
</section>
<!-- home section ends -->
<!-- about section starts  -->
<section class="about" id="about">
<h1 class="heading">about us</h1>

<div class="row">
    <div class="content">
        <h3>start your journey to a better life with our practical courses</h3>
        <p>Lessons are much more than a video call. They all happen in our tailor-made, interactive lesson space. So tutors can bring tricky concepts to life with interactive exercises, draw diagrams as they go, plus annotate homework and practice questions together. It can even make dreaded subjects - dare we say it - fun.</p>
        <a href="#"><button>learn more</button></a>
    </div>
    <div class="image">
        <img src="https://media.istockphoto.com/photos/businesswomen-working-on-line-together-picture-id909695714?b=1&k=20&m=909695714&s=170667a&w=0&h=ItlNB3GUvH6V0J_rOM2RNC_7NnfW1IHc8t8XhRfX5m4=" alt="">
    </div>
</div>
</section>
<!-- about section ends -->
<!-- teacher section starts  -->
<section id="teacher" class="teacher">
<h1 class="heading">our teachers</h1>
<h3 class="title">meet professional trainers</h3>
<div class="card-container">
    <div class="card">
        <img src="https://images.generated.photos/KIF9jaN_cHneEvyMplfVNZFcvEyaEPP3BbjJRbWKv-o/rs:fit:256:256/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/Nzc3NDM2LmpwZw.jpg" alt="">
        <h3>Ana S.</h3>
        <p>Law (Bachelors) - Cambridge University</p>
        <div class="icons">
            <a href="#" class="fab fa-facebook-f"></a>
            <a href="#" class="fab fa-twitter"></a>
            <a href="#" class="fab fa-instagram"></a>
            <a href="#" class="fab fa-github"></a>
        </div>
    </div>
    <div class="card">
        <img src="https://mktmediadev.wallstreetenglish.com/large_main_header_caucasian_man_blue_andrea2_small_bb52b9baff.jpg" alt="">
        <h3>Jivesh</h3>
        <p>French with literature (Bachelors) - Nottingham University</p>
        <div class="icons">
            <a href="#" class="fab fa-facebook-f"></a>
            <a href="#" class="fab fa-twitter"></a>
            <a href="#" class="fab fa-instagram"></a>
            <a href="#" class="fab fa-github"></a>
        </div>
    </div>
    <div class="card">
        <img src="https://images.generated.photos/A6PReTJ4FWrykRKLzQ5giwR1Ajq2dlx167aiBPwYiAQ/rs:fit:256:256/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/ODM5MjE2LmpwZw.jpg" alt="">
        <h3>Letty G.</h3>
        <p>English (Bachelors) - Birmingham University</p>
        <div class="icons">
            <a href="#" class="fab fa-facebook-f"></a>
            <a href="#" class="fab fa-twitter"></a>
            <a href="#" class="fab fa-instagram"></a>
            <a href="#" class="fab fa-github"></a>
        </div>
    </div>
    <div class="card">
        <img src="https://images.generated.photos/x5ovJYZmdY1ywRhD6i82XZ4zVoR-r3BCupxsCGLZm_w/rs:fit:256:256/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/NjM0ODYzLmpwZw.jpg" alt="">
        <h3>Elizabeth F.</h3>
        <p>Philosophy (Bachelors) - Exeter University</p>
        <div class="icons">
            <a href="#" class="fab fa-facebook-f"></a>
            <a href="#" class="fab fa-twitter"></a>
            <a href="#" class="fab fa-instagram"></a>
            <a href="#" class="fab fa-github"></a>
        </div>
    </div>
</div>
</section>
<!-- teacher section ends -->
<!-- course section starts  -->
<section id="course" class="course">
<h1 class="heading">our courses</h1>
<h3 class="title">upgrade your skills with newest courses</h3>
<div class="box-container">
    <div class="box">
        <i class="fab fa-html5"></i>
        <h3>html5</h3>
        <p>HTML5 Take this course and learn about the inner workings of an HTML form! Learn how to create your own form and integrate HTML5 validations.</p>
    </div>
    <div class="box">
        <i class="fab fa-css3-alt"></i>
        <h3>css3</h3>
        <p>Learn how to add styles websites with CSS and how to use selectors to apply styles to specific elements.</p>
    </div>
    <div class="box">
        <i class="fab fa-js-square"></i>
        <h3>javascript</h3>
        <p>Learn about what the JavaScript course has in store!</p>
    </div>
    <div class="box">
        <i class="fas fa-code"></i>
        <h3>web development</h3>
        <p>Go from no-code to an in-demand junior web developer, at a fraction of the cost of a bootcamp.</p>
    </div>
    <div class="box">
        <i class="fas fa-bullhorn"></i>
        <h3>seo marketing</h3>
        <p>Learn how to do Digital Marketing, SEO, PPC, Social Media, Content Marketing, Video Advertising, Email Marketing, Blogs.</p>
    </div>
    <div class="box">
        <i class="fas fa-paint-brush"></i>
        <h3>graphic design</h3>
        <p>Learn Photoshop, Illustrator, and InDesign by creating posters, logos, and more.</p>
    </div>
</div>
</section>
<!-- course section ends -->
<!-- review section starts  -->
<section id="review" class="review">
<h1 class="heading">students review</h1>
<h3 class="title">what our students says about us</h3>
<div class="box-container">
    <div class="box">
        <img src="https://images.generated.photos/CnsItX_iZQUqKMvtBgi3l0i_H6CrsiTZXI4WWgtQUSA/rs:fit:256:256/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/ODcxMjk1LmpwZw.jpg" alt="">
        <h3>Sara.M</h3>
        <p>"I like MyTutors because I get one-to-one support which i don't get in a classroom of 30 students."</p>
        <div class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
        </div>
    </div>
    <div class="box">
        <img src="https://images.generated.photos/nEXDGpi-uUoG-X6QjELbSnRWj4-_8IXa8uTGDpEKB8M/rs:fit:256:256/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/MjY1MjI3LmpwZw.jpg" alt="">
        <h3>Archie.T</h3>
        <p>"When i'm having tutoring, i get to be alone, in my own space and i can ask any question I want without anyone interupting me."</p>
        <div class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
        </div>
    </div>
    <div class="box">
        <img src="https://images.generated.photos/GRpR-ZExBv4uuM5V5VSAK2fWADtm6TQGVCd113E2pEc/rs:fit:256:256/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/NTc2ODczLmpwZw.jpg" alt="">
        <h3>Tom Riddle</h3>
        <p>"I really enjoy learning with my tutors every week. They build my confidence up - if I get something wrong, they tell me where I went wrong and how to do it better."</p>
        <div class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star-half-alt"></i>
        </div>
    </div>
</div>
</section>



</body>
</html>

app/views/reviews/new.html.erb
<div class="form-login">
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= simple_form_for [@course, @new_review] do |f| %>
        <%= f.input :comment %>
        <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience" %>
        <%= f.submit "Send your review" %>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container">
 <div class="d-flex row justify-content-center" style="margin: 16px;">
    <div class="wrapper">
     <div class="button">
        <div class="icon">
           <i class="fab fa-facebook-f"></i>
        </div>
        <span>Facebook</span>
     </div>
     <div class="button">
        <div class="icon">
           <i class="fab fa-twitter"></i>
        </div>
        <span>Twitter</span>
     </div>
     <div class="button">
        <div class="icon">
           <i class="fab fa-instagram"></i>
        </div>
        <span>Instagram</span>
     </div>
     <div class="button">
        <div class="icon">
           <i class="fab fa-github"></i>
        </div>
        <span>Github</span>
     </div>
     <div class="button">
        <div class="icon">
           <i class="fab fa-youtube"></i>
        </div>
        <span>YouTube</span>
     </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "" %>
    <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <nav class="nav-content">
        <a ><%= link_to "Home", "/" %></a>
        <a ><%= link_to "About", " " %></a>
        <a ><%= link_to "Courses", courses_path %></a>
        <a ><%= link_to "Contact", "#" %></a>
        <%= link_to "Bookings", bookings_path  %>
    </nav>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
     
        
        
         
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>